DROP DATABASE IF EXISTS todos;
CREATE DATABASE todos;
USE todos;

CREATE TABLE todolist (
    id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    todo VARCHAR(50) NOT NULL,
    done BOOLEAN DEFAULT false
);